[project]
name = "order-book-engine"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pybind11>=3.0.1",
    "setuptools>=80.9.0",
]
